# Generated by Django 5.2.8 on 2025-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='end',
        ),
        migrations.AddField(
            model_name='station',
            name='neighbors',
            field=models.ManyToManyField(blank=True, to='app.station'),
        ),
    ]
